package api

import (
	"fmt"
	"io"
	"log"
	"net/http"
)

/*
[
  {
    "NamHoc": "2023-2024",
    "DanhSachDiem": [
      {
        "HocKy": "HK01",
        "DanhSachDiemHK": [
          {
            "TenXepLoai": "Khá",
            "StudentID": "2312577",
            "StudentName": "TRẦN NGUYỄN TUẤN ANH",
            "StudentName_Eng": "",
            "BirthDay": "28/11/2000",
            "GenderVN": "Nam",
            "BirthPlace": "Lâm Đồng",
            "BirthPlace_Eng": "",
            "MobilePhone": "0325555077",
            "ClassStudentID": "CTK47A",
            "ClassStudentName": "CTK47A",
            "EnglishClassStudentName": null,
            "GraduateLevelID": "DH",
            "GraduateLevelName": "Đại học",
            "EnglishGraduateLevelName": "",
            "StudyTypeName": "Chính quy",
            "OlogyID": "CT",
            "OlogyName": "CÔNG NGHỆ THÔNG TIN",
            "OlogyEngName": null,
            "ScheduleStudyUnitID": "23120CT110103",
            "StudyProgramID": "CQ23CT",
            "YearStudy": "2023-2024",
            "TermID": "HK01",
            "StudyUnitID": "23120CT1101",
            "CurriculumID": "20CT1101",
            "CurriculumName": "Nhập môn ngành CNTT",
            "CurriculumNamePrint": "Nhập môn ngành CNTT",
            "EnglishCurriculumName": "Introduction to Information Technology",
            "Credits": "3",
            "CurriculumGroupID": "NC",
            "DiemTK_10": "6.6",
            "DiemTK_4": "2.0",
            "DiemTK_Chu": "C",
            "DiemChuyenMien": "",
            "IsPass": "x",
            "IsGather": "x",
            "ToanKhoa": "1",
            "NamHoc": "1",
            "HocKy": "1",
            "NotScore": "0",
            "Note": null,
            "NotComputeAverageScore": false,
            "Dat_HK": "13",
            "TB_HK": "2.62",
            "TB_HK_10": "7.18",
            "TB_HK_4": "2.62",
            "Dat_TL_HK": "13",
            "TongTC_DK_HK": "13",
            "TB_TL_HK": "2.62",
            "TB_TL_HK_10": "7.18",
            "TB_TL_HK_4": "2.62",
            "DiemRenLuyenHK": null,
            "CourseTime": "2023 - 2028",
            "ThoiGianDaoTao": "5",
            "ChuyenNganh": "Công nghệ thông tin",
            "AttendedDate": null,
            "T_TC_TL_TN": "13",
            "TB_TL_TN": "2.62",
            "TenXepLoai1": null,
            "Eng_TenXepLoai1": null,
            "SoHieuBang": null,
            "SoVaoSo": null,
            "QuyetDinhTotNghiep": "...",
            "NgayKyQuyetDinh": "...",
            "NgonNguDaoTao": null,
            "NotPrint": false,
            "KTESurvey": 0,
            "DGKS": 1,
            "SurveyClassID": "",
            "SurveyData": "",
            "ListOfProfessorID": "",
            "ListOfProfessorName": "",
            "_TermID": 3,
            "MD5": "1eabea3b0bb505fb2d6c9871684d9dc4"
          },
          {
            "TenXepLoai": "Khá",
            "StudentID": "2312577",
            "StudentName": "TRẦN NGUYỄN TUẤN ANH",
            "StudentName_Eng": "",
            "BirthDay": "28/11/2000",
            "GenderVN": "Nam",
            "BirthPlace": "Lâm Đồng",
            "BirthPlace_Eng": "",
            "MobilePhone": "0325555077",
            "ClassStudentID": "CTK47A",
            "ClassStudentName": "CTK47A",
            "EnglishClassStudentName": null,
            "GraduateLevelID": "DH",
            "GraduateLevelName": "Đại học",
            "EnglishGraduateLevelName": "",
            "StudyTypeName": "Chính quy",
            "OlogyID": "CT",
            "OlogyName": "CÔNG NGHỆ THÔNG TIN",
            "OlogyEngName": null,
            "ScheduleStudyUnitID": "23120CT110205",
            "StudyProgramID": "CQ23CT",
            "YearStudy": "2023-2024",
            "TermID": "HK01",
            "StudyUnitID": "23120CT1102",
            "CurriculumID": "20CT1102",
            "CurriculumName": "Nguyên lý lập trình cấu trúc",
            "CurriculumNamePrint": "Nguyên lý lập trình cấu trúc",
            "EnglishCurriculumName": "Structural programming principles",
            "Credits": "4",
            "CurriculumGroupID": "NC",
            "DiemTK_10": "9.1",
            "DiemTK_4": "4.0",
            "DiemTK_Chu": "A",
            "DiemChuyenMien": "",
            "IsPass": "x",
            "IsGather": "x",
            "ToanKhoa": "1",
            "NamHoc": "1",
            "HocKy": "1",
            "NotScore": "0",
            "Note": null,
            "NotComputeAverageScore": false,
            "Dat_HK": "13",
            "TB_HK": "2.62",
            "TB_HK_10": "7.18",
            "TB_HK_4": "2.62",
            "Dat_TL_HK": "13",
            "TongTC_DK_HK": "13",
            "TB_TL_HK": "2.62",
            "TB_TL_HK_10": "7.18",
            "TB_TL_HK_4": "2.62",
            "DiemRenLuyenHK": null,
            "CourseTime": "2023 - 2028",
            "ThoiGianDaoTao": "5",
            "ChuyenNganh": "Công nghệ thông tin",
            "AttendedDate": null,
            "T_TC_TL_TN": "13",
            "TB_TL_TN": "2.62",
            "TenXepLoai1": null,
            "Eng_TenXepLoai1": null,
            "SoHieuBang": null,
            "SoVaoSo": null,
            "QuyetDinhTotNghiep": "...",
            "NgayKyQuyetDinh": "...",
            "NgonNguDaoTao": null,
            "NotPrint": false,
            "KTESurvey": 0,
            "DGKS": 1,
            "SurveyClassID": "",
            "SurveyData": "",
            "ListOfProfessorID": "",
            "ListOfProfessorName": "",
            "_TermID": 3,
            "MD5": "3cfe0f8da2de3258ab5b7ff876d282af"
          },
          {
            "TenXepLoai": "Khá",
            "StudentID": "2312577",
            "StudentName": "TRẦN NGUYỄN TUẤN ANH",
            "StudentName_Eng": "",
            "BirthDay": "28/11/2000",
            "GenderVN": "Nam",
            "BirthPlace": "Lâm Đồng",
            "BirthPlace_Eng": "",
            "MobilePhone": "0325555077",
            "ClassStudentID": "CTK47A",
            "ClassStudentName": "CTK47A",
            "EnglishClassStudentName": null,
            "GraduateLevelID": "DH",
            "GraduateLevelName": "Đại học",
            "EnglishGraduateLevelName": "",
            "StudyTypeName": "Chính quy",
            "OlogyID": "CT",
            "OlogyName": "CÔNG NGHỆ THÔNG TIN",
            "OlogyEngName": null,
            "ScheduleStudyUnitID": "23120LH000110",
            "StudyProgramID": "CQ23CT",
            "YearStudy": "2023-2024",
            "TermID": "HK01",
            "StudyUnitID": "23120LH0001",
            "CurriculumID": "20LH0001",
            "CurriculumName": "Pháp luật đại cương",
            "CurriculumNamePrint": "Pháp luật đại cương",
            "EnglishCurriculumName": "Introduction to laws",
            "Credits": "3",
            "CurriculumGroupID": "NC",
            "DiemTK_10": "6.0",
            "DiemTK_4": "2.0",
            "DiemTK_Chu": "C",
            "DiemChuyenMien": "",
            "IsPass": "x",
            "IsGather": "x",
            "ToanKhoa": "1",
            "NamHoc": "1",
            "HocKy": "1",
            "NotScore": "0",
            "Note": null,
            "NotComputeAverageScore": false,
            "Dat_HK": "13",
            "TB_HK": "2.62",
            "TB_HK_10": "7.18",
            "TB_HK_4": "2.62",
            "Dat_TL_HK": "13",
            "TongTC_DK_HK": "13",
            "TB_TL_HK": "2.62",
            "TB_TL_HK_10": "7.18",
            "TB_TL_HK_4": "2.62",
            "DiemRenLuyenHK": null,
            "CourseTime": "2023 - 2028",
            "ThoiGianDaoTao": "5",
            "ChuyenNganh": "Công nghệ thông tin",
            "AttendedDate": null,
            "T_TC_TL_TN": "13",
            "TB_TL_TN": "2.62",
            "TenXepLoai1": null,
            "Eng_TenXepLoai1": null,
            "SoHieuBang": null,
            "SoVaoSo": null,
            "QuyetDinhTotNghiep": "...",
            "NgayKyQuyetDinh": "...",
            "NgonNguDaoTao": null,
            "NotPrint": false,
            "KTESurvey": 0,
            "DGKS": 1,
            "SurveyClassID": "",
            "SurveyData": "",
            "ListOfProfessorID": "",
            "ListOfProfessorName": "",
            "_TermID": 3,
            "MD5": "012e003c73cb80ef6ce9122cedb13963"
          },
          {
            "TenXepLoai": "Khá",
            "StudentID": "2312577",
            "StudentName": "TRẦN NGUYỄN TUẤN ANH",
            "StudentName_Eng": "",
            "BirthDay": "28/11/2000",
            "GenderVN": "Nam",
            "BirthPlace": "Lâm Đồng",
            "BirthPlace_Eng": "",
            "MobilePhone": "0325555077",
            "ClassStudentID": "CTK47A",
            "ClassStudentName": "CTK47A",
            "EnglishClassStudentName": null,
            "GraduateLevelID": "DH",
            "GraduateLevelName": "Đại học",
            "EnglishGraduateLevelName": "",
            "StudyTypeName": "Chính quy",
            "OlogyID": "CT",
            "OlogyName": "CÔNG NGHỆ THÔNG TIN",
            "OlogyEngName": null,
            "ScheduleStudyUnitID": "231LC1101D46",
            "StudyProgramID": "CQ23CT",
            "YearStudy": "2023-2024",
            "TermID": "HK01",
            "StudyUnitID": "231LC1101D",
            "CurriculumID": "LC1101D",
            "CurriculumName": "Triết học Mác - Lênin",
            "CurriculumNamePrint": "Triết học Mác - Lênin",
            "EnglishCurriculumName": "Philosophy of Marxism and Leninism",
            "Credits": "3",
            "CurriculumGroupID": "NC",
            "DiemTK_10": "6.4",
            "DiemTK_4": "2.0",
            "DiemTK_Chu": "C",
            "DiemChuyenMien": "",
            "IsPass": "x",
            "IsGather": "x",
            "ToanKhoa": "1",
            "NamHoc": "1",
            "HocKy": "1",
            "NotScore": "0",
            "Note": null,
            "NotComputeAverageScore": false,
            "Dat_HK": "13",
            "TB_HK": "2.62",
            "TB_HK_10": "7.18",
            "TB_HK_4": "2.62",
            "Dat_TL_HK": "13",
            "TongTC_DK_HK": "13",
            "TB_TL_HK": "2.62",
            "TB_TL_HK_10": "7.18",
            "TB_TL_HK_4": "2.62",
            "DiemRenLuyenHK": null,
            "CourseTime": "2023 - 2028",
            "ThoiGianDaoTao": "5",
            "ChuyenNganh": "Công nghệ thông tin",
            "AttendedDate": null,
            "T_TC_TL_TN": "13",
            "TB_TL_TN": "2.62",
            "TenXepLoai1": null,
            "Eng_TenXepLoai1": null,
            "SoHieuBang": null,
            "SoVaoSo": null,
            "QuyetDinhTotNghiep": "...",
            "NgayKyQuyetDinh": "...",
            "NgonNguDaoTao": null,
            "NotPrint": false,
            "KTESurvey": 0,
            "DGKS": 1,
            "SurveyClassID": "",
            "SurveyData": "",
            "ListOfProfessorID": "",
            "ListOfProfessorName": "",
            "_TermID": 3,
            "MD5": "9637436704c1723cfff6b31017f5d941"
          },
          {
            "TenXepLoai": "Khá",
            "StudentID": "2312577",
            "StudentName": "TRẦN NGUYỄN TUẤN ANH",
            "StudentName_Eng": "",
            "BirthDay": "28/11/2000",
            "GenderVN": "Nam",
            "BirthPlace": "Lâm Đồng",
            "BirthPlace_Eng": "",
            "MobilePhone": "0325555077",
            "ClassStudentID": "CTK47A",
            "ClassStudentName": "CTK47A",
            "EnglishClassStudentName": null,
            "GraduateLevelID": "DH",
            "GraduateLevelName": "Đại học",
            "EnglishGraduateLevelName": "",
            "StudyTypeName": "Chính quy",
            "OlogyID": "CT",
            "OlogyName": "CÔNG NGHỆ THÔNG TIN",
            "OlogyEngName": null,
            "ScheduleStudyUnitID": "231QP2101D01",
            "StudyProgramID": "CQ23CT",
            "YearStudy": "2023-2024",
            "TermID": "HK01",
            "StudyUnitID": "231QP2101D",
            "CurriculumID": "QP2101D",
            "CurriculumName": "Giáo dục quốc phòng và an ninh 1 <span style=\"color:red\">*</span>",
            "CurriculumNamePrint": "Giáo dục quốc phòng và an ninh 1 *",
            "EnglishCurriculumName": "National defense - security education 1",
            "Credits": "3",
            "CurriculumGroupID": "DC",
            "DiemTK_10": "5.0",
            "DiemTK_4": "1.0",
            "DiemTK_Chu": "D",
            "DiemChuyenMien": "",
            "IsPass": "x",
            "IsGather": "x",
            "ToanKhoa": "1",
            "NamHoc": "1",
            "HocKy": "1",
            "NotScore": "0",
            "Note": null,
            "NotComputeAverageScore": true,
            "Dat_HK": "13",
            "TB_HK": "2.62",
            "TB_HK_10": "7.18",
            "TB_HK_4": "2.62",
            "Dat_TL_HK": "13",
            "TongTC_DK_HK": "13",
            "TB_TL_HK": "2.62",
            "TB_TL_HK_10": "7.18",
            "TB_TL_HK_4": "2.62",
            "DiemRenLuyenHK": null,
            "CourseTime": "2023 - 2028",
            "ThoiGianDaoTao": "5",
            "ChuyenNganh": "Công nghệ thông tin",
            "AttendedDate": null,
            "T_TC_TL_TN": "13",
            "TB_TL_TN": "2.62",
            "TenXepLoai1": null,
            "Eng_TenXepLoai1": null,
            "SoHieuBang": null,
            "SoVaoSo": null,
            "QuyetDinhTotNghiep": "...",
            "NgayKyQuyetDinh": "...",
            "NgonNguDaoTao": null,
            "NotPrint": false,
            "KTESurvey": 0,
            "DGKS": 1,
            "SurveyClassID": "",
            "SurveyData": "",
            "ListOfProfessorID": "",
            "ListOfProfessorName": "",
            "_TermID": 3,
            "MD5": "4b68218949dd6ed245feed120240ba99"
          },
          {
            "TenXepLoai": "Khá",
            "StudentID": "2312577",
            "StudentName": "TRẦN NGUYỄN TUẤN ANH",
            "StudentName_Eng": "",
            "BirthDay": "28/11/2000",
            "GenderVN": "Nam",
            "BirthPlace": "Lâm Đồng",
            "BirthPlace_Eng": "",
            "MobilePhone": "0325555077",
            "ClassStudentID": "CTK47A",
            "ClassStudentName": "CTK47A",
            "EnglishClassStudentName": null,
            "GraduateLevelID": "DH",
            "GraduateLevelName": "Đại học",
            "EnglishGraduateLevelName": "",
            "StudyTypeName": "Chính quy",
            "OlogyID": "CT",
            "OlogyName": "CÔNG NGHỆ THÔNG TIN",
            "OlogyEngName": null,
            "ScheduleStudyUnitID": "231QP2102D01",
            "StudyProgramID": "CQ23CT",
            "YearStudy": "2023-2024",
            "TermID": "HK01",
            "StudyUnitID": "231QP2102D",
            "CurriculumID": "QP2102D",
            "CurriculumName": "Giáo dục quốc phòng và an ninh 2 <span style=\"color:red\">*</span>",
            "CurriculumNamePrint": "Giáo dục quốc phòng và an ninh 2 *",
            "EnglishCurriculumName": "National defense - security education 2",
            "Credits": "2",
            "CurriculumGroupID": "DC",
            "DiemTK_10": "6.5",
            "DiemTK_4": "2.0",
            "DiemTK_Chu": "C",
            "DiemChuyenMien": "",
            "IsPass": "x",
            "IsGather": "x",
            "ToanKhoa": "1",
            "NamHoc": "1",
            "HocKy": "1",
            "NotScore": "0",
            "Note": null,
            "NotComputeAverageScore": true,
            "Dat_HK": "13",
            "TB_HK": "2.62",
            "TB_HK_10": "7.18",
            "TB_HK_4": "2.62",
            "Dat_TL_HK": "13",
            "TongTC_DK_HK": "13",
            "TB_TL_HK": "2.62",
            "TB_TL_HK_10": "7.18",
            "TB_TL_HK_4": "2.62",
            "DiemRenLuyenHK": null,
            "CourseTime": "2023 - 2028",
            "ThoiGianDaoTao": "5",
            "ChuyenNganh": "Công nghệ thông tin",
            "AttendedDate": null,
            "T_TC_TL_TN": "13",
            "TB_TL_TN": "2.62",
            "TenXepLoai1": null,
            "Eng_TenXepLoai1": null,
            "SoHieuBang": null,
            "SoVaoSo": null,
            "QuyetDinhTotNghiep": "...",
            "NgayKyQuyetDinh": "...",
            "NgonNguDaoTao": null,
            "NotPrint": false,
            "KTESurvey": 0,
            "DGKS": 1,
            "SurveyClassID": "",
            "SurveyData": "",
            "ListOfProfessorID": "",
            "ListOfProfessorName": "",
            "_TermID": 3,
            "MD5": "c908942e61567a039c4577911b577cb7"
          },
          {
            "TenXepLoai": "Khá",
            "StudentID": "2312577",
            "StudentName": "TRẦN NGUYỄN TUẤN ANH",
            "StudentName_Eng": "",
            "BirthDay": "28/11/2000",
            "GenderVN": "Nam",
            "BirthPlace": "Lâm Đồng",
            "BirthPlace_Eng": "",
            "MobilePhone": "0325555077",
            "ClassStudentID": "CTK47A",
            "ClassStudentName": "CTK47A",
            "EnglishClassStudentName": null,
            "GraduateLevelID": "DH",
            "GraduateLevelName": "Đại học",
            "EnglishGraduateLevelName": "",
            "StudyTypeName": "Chính quy",
            "OlogyID": "CT",
            "OlogyName": "CÔNG NGHỆ THÔNG TIN",
            "OlogyEngName": null,
            "ScheduleStudyUnitID": "231QP2103D49",
            "StudyProgramID": "CQ23CT",
            "YearStudy": "2023-2024",
            "TermID": "HK01",
            "StudyUnitID": "231QP2103D",
            "CurriculumID": "QP2103D",
            "CurriculumName": "Giáo dục quốc phòng và an ninh 3 <span style=\"color:red\">*</span>",
            "CurriculumNamePrint": "Giáo dục quốc phòng và an ninh 3 *",
            "EnglishCurriculumName": "National defense - security education 3",
            "Credits": "2",
            "CurriculumGroupID": "DC",
            "DiemTK_10": "8.0",
            "DiemTK_4": "3.0",
            "DiemTK_Chu": "B",
            "DiemChuyenMien": "",
            "IsPass": "x",
            "IsGather": "x",
            "ToanKhoa": "1",
            "NamHoc": "1",
            "HocKy": "1",
            "NotScore": "0",
            "Note": null,
            "NotComputeAverageScore": true,
            "Dat_HK": "13",
            "TB_HK": "2.62",
            "TB_HK_10": "7.18",
            "TB_HK_4": "2.62",
            "Dat_TL_HK": "13",
            "TongTC_DK_HK": "13",
            "TB_TL_HK": "2.62",
            "TB_TL_HK_10": "7.18",
            "TB_TL_HK_4": "2.62",
            "DiemRenLuyenHK": null,
            "CourseTime": "2023 - 2028",
            "ThoiGianDaoTao": "5",
            "ChuyenNganh": "Công nghệ thông tin",
            "AttendedDate": null,
            "T_TC_TL_TN": "13",
            "TB_TL_TN": "2.62",
            "TenXepLoai1": null,
            "Eng_TenXepLoai1": null,
            "SoHieuBang": null,
            "SoVaoSo": null,
            "QuyetDinhTotNghiep": "...",
            "NgayKyQuyetDinh": "...",
            "NgonNguDaoTao": null,
            "NotPrint": false,
            "KTESurvey": 0,
            "DGKS": 1,
            "SurveyClassID": "",
            "SurveyData": "",
            "ListOfProfessorID": "",
            "ListOfProfessorName": "",
            "_TermID": 3,
            "MD5": "09c9fa865d8a687fa439f8be8955b4ae"
          },
          {
            "TenXepLoai": "Khá",
            "StudentID": "2312577",
            "StudentName": "TRẦN NGUYỄN TUẤN ANH",
            "StudentName_Eng": "",
            "BirthDay": "28/11/2000",
            "GenderVN": "Nam",
            "BirthPlace": "Lâm Đồng",
            "BirthPlace_Eng": "",
            "MobilePhone": "0325555077",
            "ClassStudentID": "CTK47A",
            "ClassStudentName": "CTK47A",
            "EnglishClassStudentName": null,
            "GraduateLevelID": "DH",
            "GraduateLevelName": "Đại học",
            "EnglishGraduateLevelName": "",
            "StudyTypeName": "Chính quy",
            "OlogyID": "CT",
            "OlogyName": "CÔNG NGHỆ THÔNG TIN",
            "OlogyEngName": null,
            "ScheduleStudyUnitID": "231QP2104D25",
            "StudyProgramID": "CQ23CT",
            "YearStudy": "2023-2024",
            "TermID": "HK01",
            "StudyUnitID": "231QP2104D",
            "CurriculumID": "QP2104D",
            "CurriculumName": "Giáo dục quốc phòng và an ninh 4 (Thực hành) <span style=\"color:red\">*</span>",
            "CurriculumNamePrint": "Giáo dục quốc phòng và an ninh 4 (Thực hành) *",
            "EnglishCurriculumName": "National defense - security education 4",
            "Credits": "2",
            "CurriculumGroupID": "DC",
            "DiemTK_10": "7.5",
            "DiemTK_4": "3.0",
            "DiemTK_Chu": "B",
            "DiemChuyenMien": "",
            "IsPass": "x",
            "IsGather": "x",
            "ToanKhoa": "1",
            "NamHoc": "1",
            "HocKy": "1",
            "NotScore": "0",
            "Note": null,
            "NotComputeAverageScore": true,
            "Dat_HK": "13",
            "TB_HK": "2.62",
            "TB_HK_10": "7.18",
            "TB_HK_4": "2.62",
            "Dat_TL_HK": "13",
            "TongTC_DK_HK": "13",
            "TB_TL_HK": "2.62",
            "TB_TL_HK_10": "7.18",
            "TB_TL_HK_4": "2.62",
            "DiemRenLuyenHK": null,
            "CourseTime": "2023 - 2028",
            "ThoiGianDaoTao": "5",
            "ChuyenNganh": "Công nghệ thông tin",
            "AttendedDate": null,
            "T_TC_TL_TN": "13",
            "TB_TL_TN": "2.62",
            "TenXepLoai1": null,
            "Eng_TenXepLoai1": null,
            "SoHieuBang": null,
            "SoVaoSo": null,
            "QuyetDinhTotNghiep": "...",
            "NgayKyQuyetDinh": "...",
            "NgonNguDaoTao": null,
            "NotPrint": false,
            "KTESurvey": 0,
            "DGKS": 1,
            "SurveyClassID": "",
            "SurveyData": "",
            "ListOfProfessorID": "",
            "ListOfProfessorName": "",
            "_TermID": 3,
            "MD5": "75bc759717014b2457f245c970515399"
          },
          {
            "TenXepLoai": "Khá",
            "StudentID": "2312577",
            "StudentName": "TRẦN NGUYỄN TUẤN ANH",
            "StudentName_Eng": "",
            "BirthDay": "28/11/2000",
            "GenderVN": "Nam",
            "BirthPlace": "Lâm Đồng",
            "BirthPlace_Eng": "",
            "MobilePhone": "0325555077",
            "ClassStudentID": "CTK47A",
            "ClassStudentName": "CTK47A",
            "EnglishClassStudentName": null,
            "GraduateLevelID": "DH",
            "GraduateLevelName": "Đại học",
            "EnglishGraduateLevelName": "",
            "StudyTypeName": "Chính quy",
            "OlogyID": "CT",
            "OlogyName": "CÔNG NGHỆ THÔNG TIN",
            "OlogyEngName": null,
            "ScheduleStudyUnitID": "231TC1001D34",
            "StudyProgramID": "CQ23CT",
            "YearStudy": "2023-2024",
            "TermID": "HK01",
            "StudyUnitID": "231TC1001D",
            "CurriculumID": "TC1001D",
            "CurriculumName": "Giáo dục thể chất 1 (Thực hành) <span style=\"color:red\">*</span>",
            "CurriculumNamePrint": "Giáo dục thể chất 1 (Thực hành) *",
            "EnglishCurriculumName": "Physical Education 1",
            "Credits": "1",
            "CurriculumGroupID": "PC",
            "DiemTK_10": "6.0",
            "DiemTK_4": "2.0",
            "DiemTK_Chu": "C",
            "DiemChuyenMien": "",
            "IsPass": "x",
            "IsGather": "x",
            "ToanKhoa": "1",
            "NamHoc": "1",
            "HocKy": "1",
            "NotScore": "0",
            "Note": null,
            "NotComputeAverageScore": true,
            "Dat_HK": "13",
            "TB_HK": "2.62",
            "TB_HK_10": "7.18",
            "TB_HK_4": "2.62",
            "Dat_TL_HK": "13",
            "TongTC_DK_HK": "13",
            "TB_TL_HK": "2.62",
            "TB_TL_HK_10": "7.18",
            "TB_TL_HK_4": "2.62",
            "DiemRenLuyenHK": null,
            "CourseTime": "2023 - 2028",
            "ThoiGianDaoTao": "5",
            "ChuyenNganh": "Công nghệ thông tin",
            "AttendedDate": null,
            "T_TC_TL_TN": "13",
            "TB_TL_TN": "2.62",
            "TenXepLoai1": null,
            "Eng_TenXepLoai1": null,
            "SoHieuBang": null,
            "SoVaoSo": null,
            "QuyetDinhTotNghiep": "...",
            "NgayKyQuyetDinh": "...",
            "NgonNguDaoTao": null,
            "NotPrint": false,
            "KTESurvey": 0,
            "DGKS": 1,
            "SurveyClassID": "",
            "SurveyData": "",
            "ListOfProfessorID": "",
            "ListOfProfessorName": "",
            "_TermID": 3,
            "MD5": "102c677497a4541bc284b14f11e1efa4"
          }
        ]
      },
      {
        "HocKy": "HK02",
        "DanhSachDiemHK": [
          {
            "TenXepLoai": "Khá",
            "StudentID": "2312577",
            "StudentName": "TRẦN NGUYỄN TUẤN ANH",
            "StudentName_Eng": "",
            "BirthDay": "28/11/2000",
            "GenderVN": "Nam",
            "BirthPlace": "Lâm Đồng",
            "BirthPlace_Eng": "",
            "MobilePhone": "0325555077",
            "ClassStudentID": "CTK47A",
            "ClassStudentName": "CTK47A",
            "EnglishClassStudentName": null,
            "GraduateLevelID": "DH",
            "GraduateLevelName": "Đại học",
            "EnglishGraduateLevelName": "",
            "StudyTypeName": "Chính quy",
            "OlogyID": "CT",
            "OlogyName": "CÔNG NGHỆ THÔNG TIN",
            "OlogyEngName": null,
            "ScheduleStudyUnitID": "23220CT110302",
            "StudyProgramID": "CQ23CT",
            "YearStudy": "2023-2024",
            "TermID": "HK02",
            "StudyUnitID": "23220CT1103",
            "CurriculumID": "20CT1103",
            "CurriculumName": "Bảo trì máy tính",
            "CurriculumNamePrint": "Bảo trì máy tính",
            "EnglishCurriculumName": "Computer Maintenance",
            "Credits": "3",
            "CurriculumGroupID": "NC",
            "DiemTK_10": null,
            "DiemTK_4": null,
            "DiemTK_Chu": null,
            "DiemChuyenMien": "",
            "IsPass": null,
            "IsGather": "x",
            "ToanKhoa": "1",
            "NamHoc": "1",
            "HocKy": "1",
            "NotScore": "1",
            "Note": null,
            "NotComputeAverageScore": false,
            "Dat_HK": null,
            "TB_HK": null,
            "TB_HK_10": null,
            "TB_HK_4": null,
            "Dat_TL_HK": "13",
            "TongTC_DK_HK": "13",
            "TB_TL_HK": "2.62",
            "TB_TL_HK_10": "7.18",
            "TB_TL_HK_4": "2.62",
            "DiemRenLuyenHK": null,
            "CourseTime": "2023 - 2028",
            "ThoiGianDaoTao": "5",
            "ChuyenNganh": "Công nghệ thông tin",
            "AttendedDate": null,
            "T_TC_TL_TN": "13",
            "TB_TL_TN": "2.62",
            "TenXepLoai1": null,
            "Eng_TenXepLoai1": null,
            "SoHieuBang": null,
            "SoVaoSo": null,
            "QuyetDinhTotNghiep": "...",
            "NgayKyQuyetDinh": "...",
            "NgonNguDaoTao": null,
            "NotPrint": false,
            "KTESurvey": 0,
            "DGKS": 1,
            "SurveyClassID": "",
            "SurveyData": "",
            "ListOfProfessorID": "",
            "ListOfProfessorName": "",
            "_TermID": 3,
            "MD5": "8bd34853d8a17398e7fdb17f66429bcb"
          },
          {
            "TenXepLoai": "Khá",
            "StudentID": "2312577",
            "StudentName": "TRẦN NGUYỄN TUẤN ANH",
            "StudentName_Eng": "",
            "BirthDay": "28/11/2000",
            "GenderVN": "Nam",
            "BirthPlace": "Lâm Đồng",
            "BirthPlace_Eng": "",
            "MobilePhone": "0325555077",
            "ClassStudentID": "CTK47A",
            "ClassStudentName": "CTK47A",
            "EnglishClassStudentName": null,
            "GraduateLevelID": "DH",
            "GraduateLevelName": "Đại học",
            "EnglishGraduateLevelName": "",
            "StudyTypeName": "Chính quy",
            "OlogyID": "CT",
            "OlogyName": "CÔNG NGHỆ THÔNG TIN",
            "OlogyEngName": null,
            "ScheduleStudyUnitID": "23220CT120202",
            "StudyProgramID": "CQ23CT",
            "YearStudy": "2023-2024",
            "TermID": "HK02",
            "StudyUnitID": "23220CT1202",
            "CurriculumID": "20CT1202",
            "CurriculumName": "Nguyên lý lập trình hướng đối tượng",
            "CurriculumNamePrint": "Nguyên lý lập trình hướng đối tượng",
            "EnglishCurriculumName": "Object-oriented programming principles",
            "Credits": "4",
            "CurriculumGroupID": "NC",
            "DiemTK_10": null,
            "DiemTK_4": null,
            "DiemTK_Chu": null,
            "DiemChuyenMien": "",
            "IsPass": null,
            "IsGather": "x",
            "ToanKhoa": "1",
            "NamHoc": "1",
            "HocKy": "1",
            "NotScore": "1",
            "Note": null,
            "NotComputeAverageScore": false,
            "Dat_HK": null,
            "TB_HK": null,
            "TB_HK_10": null,
            "TB_HK_4": null,
            "Dat_TL_HK": "13",
            "TongTC_DK_HK": "13",
            "TB_TL_HK": "2.62",
            "TB_TL_HK_10": "7.18",
            "TB_TL_HK_4": "2.62",
            "DiemRenLuyenHK": null,
            "CourseTime": "2023 - 2028",
            "ThoiGianDaoTao": "5",
            "ChuyenNganh": "Công nghệ thông tin",
            "AttendedDate": null,
            "T_TC_TL_TN": "13",
            "TB_TL_TN": "2.62",
            "TenXepLoai1": null,
            "Eng_TenXepLoai1": null,
            "SoHieuBang": null,
            "SoVaoSo": null,
            "QuyetDinhTotNghiep": "...",
            "NgayKyQuyetDinh": "...",
            "NgonNguDaoTao": null,
            "NotPrint": false,
            "KTESurvey": 0,
            "DGKS": 1,
            "SurveyClassID": "",
            "SurveyData": "",
            "ListOfProfessorID": "",
            "ListOfProfessorName": "",
            "_TermID": 3,
            "MD5": "4fc242484e3a54722a4ef25ebe08cb58"
          },
          {
            "TenXepLoai": "Khá",
            "StudentID": "2312577",
            "StudentName": "TRẦN NGUYỄN TUẤN ANH",
            "StudentName_Eng": "",
            "BirthDay": "28/11/2000",
            "GenderVN": "Nam",
            "BirthPlace": "Lâm Đồng",
            "BirthPlace_Eng": "",
            "MobilePhone": "0325555077",
            "ClassStudentID": "CTK47A",
            "ClassStudentName": "CTK47A",
            "EnglishClassStudentName": null,
            "GraduateLevelID": "DH",
            "GraduateLevelName": "Đại học",
            "EnglishGraduateLevelName": "",
            "StudyTypeName": "Chính quy",
            "OlogyID": "CT",
            "OlogyName": "CÔNG NGHỆ THÔNG TIN",
            "OlogyEngName": null,
            "ScheduleStudyUnitID": "23220CT120302",
            "StudyProgramID": "CQ23CT",
            "YearStudy": "2023-2024",
            "TermID": "HK02",
            "StudyUnitID": "23220CT1203",
            "CurriculumID": "20CT1203",
            "CurriculumName": "Đồ họa ứng dụng",
            "CurriculumNamePrint": "Đồ họa ứng dụng",
            "EnglishCurriculumName": "Applied graphics",
            "Credits": "3",
            "CurriculumGroupID": "NC",
            "DiemTK_10": null,
            "DiemTK_4": null,
            "DiemTK_Chu": null,
            "DiemChuyenMien": "",
            "IsPass": null,
            "IsGather": "x",
            "ToanKhoa": "1",
            "NamHoc": "1",
            "HocKy": "1",
            "NotScore": "1",
            "Note": null,
            "NotComputeAverageScore": false,
            "Dat_HK": null,
            "TB_HK": null,
            "TB_HK_10": null,
            "TB_HK_4": null,
            "Dat_TL_HK": "13",
            "TongTC_DK_HK": "13",
            "TB_TL_HK": "2.62",
            "TB_TL_HK_10": "7.18",
            "TB_TL_HK_4": "2.62",
            "DiemRenLuyenHK": null,
            "CourseTime": "2023 - 2028",
            "ThoiGianDaoTao": "5",
            "ChuyenNganh": "Công nghệ thông tin",
            "AttendedDate": null,
            "T_TC_TL_TN": "13",
            "TB_TL_TN": "2.62",
            "TenXepLoai1": null,
            "Eng_TenXepLoai1": null,
            "SoHieuBang": null,
            "SoVaoSo": null,
            "QuyetDinhTotNghiep": "...",
            "NgayKyQuyetDinh": "...",
            "NgonNguDaoTao": null,
            "NotPrint": false,
            "KTESurvey": 0,
            "DGKS": 1,
            "SurveyClassID": "",
            "SurveyData": "",
            "ListOfProfessorID": "",
            "ListOfProfessorName": "",
            "_TermID": 3,
            "MD5": "75f4f53e36cb7f9b06602b3fc5d968ce"
          },
          {
            "TenXepLoai": "Khá",
            "StudentID": "2312577",
            "StudentName": "TRẦN NGUYỄN TUẤN ANH",
            "StudentName_Eng": "",
            "BirthDay": "28/11/2000",
            "GenderVN": "Nam",
            "BirthPlace": "Lâm Đồng",
            "BirthPlace_Eng": "",
            "MobilePhone": "0325555077",
            "ClassStudentID": "CTK47A",
            "ClassStudentName": "CTK47A",
            "EnglishClassStudentName": null,
            "GraduateLevelID": "DH",
            "GraduateLevelName": "Đại học",
            "EnglishGraduateLevelName": "",
            "StudyTypeName": "Chính quy",
            "OlogyID": "CT",
            "OlogyName": "CÔNG NGHỆ THÔNG TIN",
            "OlogyEngName": null,
            "ScheduleStudyUnitID": "23220TN120102",
            "StudyProgramID": "CQ23CT",
            "YearStudy": "2023-2024",
            "TermID": "HK02",
            "StudyUnitID": "23220TN1201",
            "CurriculumID": "20TN1201",
            "CurriculumName": "Toán cao cấp B1",
            "CurriculumNamePrint": "Toán cao cấp B1",
            "EnglishCurriculumName": "Advanced Mathematics B1",
            "Credits": "3",
            "CurriculumGroupID": "NC",
            "DiemTK_10": null,
            "DiemTK_4": null,
            "DiemTK_Chu": null,
            "DiemChuyenMien": "",
            "IsPass": null,
            "IsGather": "x",
            "ToanKhoa": "1",
            "NamHoc": "1",
            "HocKy": "1",
            "NotScore": "1",
            "Note": null,
            "NotComputeAverageScore": false,
            "Dat_HK": null,
            "TB_HK": null,
            "TB_HK_10": null,
            "TB_HK_4": null,
            "Dat_TL_HK": "13",
            "TongTC_DK_HK": "13",
            "TB_TL_HK": "2.62",
            "TB_TL_HK_10": "7.18",
            "TB_TL_HK_4": "2.62",
            "DiemRenLuyenHK": null,
            "CourseTime": "2023 - 2028",
            "ThoiGianDaoTao": "5",
            "ChuyenNganh": "Công nghệ thông tin",
            "AttendedDate": null,
            "T_TC_TL_TN": "13",
            "TB_TL_TN": "2.62",
            "TenXepLoai1": null,
            "Eng_TenXepLoai1": null,
            "SoHieuBang": null,
            "SoVaoSo": null,
            "QuyetDinhTotNghiep": "...",
            "NgayKyQuyetDinh": "...",
            "NgonNguDaoTao": null,
            "NotPrint": false,
            "KTESurvey": 0,
            "DGKS": 1,
            "SurveyClassID": "",
            "SurveyData": "",
            "ListOfProfessorID": "",
            "ListOfProfessorName": "",
            "_TermID": 3,
            "MD5": "080641491b1c3648c036450cf1254074"
          },
          {
            "TenXepLoai": "Khá",
            "StudentID": "2312577",
            "StudentName": "TRẦN NGUYỄN TUẤN ANH",
            "StudentName_Eng": "",
            "BirthDay": "28/11/2000",
            "GenderVN": "Nam",
            "BirthPlace": "Lâm Đồng",
            "BirthPlace_Eng": "",
            "MobilePhone": "0325555077",
            "ClassStudentID": "CTK47A",
            "ClassStudentName": "CTK47A",
            "EnglishClassStudentName": null,
            "GraduateLevelID": "DH",
            "GraduateLevelName": "Đại học",
            "EnglishGraduateLevelName": "",
            "StudyTypeName": "Chính quy",
            "OlogyID": "CT",
            "OlogyName": "CÔNG NGHỆ THÔNG TIN",
            "OlogyEngName": null,
            "ScheduleStudyUnitID": "23220TN120202",
            "StudyProgramID": "CQ23CT",
            "YearStudy": "2023-2024",
            "TermID": "HK02",
            "StudyUnitID": "23220TN1202",
            "CurriculumID": "20TN1202",
            "CurriculumName": "Toán rời rạc",
            "CurriculumNamePrint": "Toán rời rạc",
            "EnglishCurriculumName": "Discrete Mathematics",
            "Credits": "4",
            "CurriculumGroupID": "NC",
            "DiemTK_10": null,
            "DiemTK_4": null,
            "DiemTK_Chu": null,
            "DiemChuyenMien": "",
            "IsPass": null,
            "IsGather": "x",
            "ToanKhoa": "1",
            "NamHoc": "1",
            "HocKy": "1",
            "NotScore": "1",
            "Note": null,
            "NotComputeAverageScore": false,
            "Dat_HK": null,
            "TB_HK": null,
            "TB_HK_10": null,
            "TB_HK_4": null,
            "Dat_TL_HK": "13",
            "TongTC_DK_HK": "13",
            "TB_TL_HK": "2.62",
            "TB_TL_HK_10": "7.18",
            "TB_TL_HK_4": "2.62",
            "DiemRenLuyenHK": null,
            "CourseTime": "2023 - 2028",
            "ThoiGianDaoTao": "5",
            "ChuyenNganh": "Công nghệ thông tin",
            "AttendedDate": null,
            "T_TC_TL_TN": "13",
            "TB_TL_TN": "2.62",
            "TenXepLoai1": null,
            "Eng_TenXepLoai1": null,
            "SoHieuBang": null,
            "SoVaoSo": null,
            "QuyetDinhTotNghiep": "...",
            "NgayKyQuyetDinh": "...",
            "NgonNguDaoTao": null,
            "NotPrint": false,
            "KTESurvey": 0,
            "DGKS": 1,
            "SurveyClassID": "",
            "SurveyData": "",
            "ListOfProfessorID": "",
            "ListOfProfessorName": "",
            "_TermID": 3,
            "MD5": "4d96e1c2197b3fca358896173a69992d"
          },
          {
            "TenXepLoai": "Khá",
            "StudentID": "2312577",
            "StudentName": "TRẦN NGUYỄN TUẤN ANH",
            "StudentName_Eng": "",
            "BirthDay": "28/11/2000",
            "GenderVN": "Nam",
            "BirthPlace": "Lâm Đồng",
            "BirthPlace_Eng": "",
            "MobilePhone": "0325555077",
            "ClassStudentID": "CTK47A",
            "ClassStudentName": "CTK47A",
            "EnglishClassStudentName": null,
            "GraduateLevelID": "DH",
            "GraduateLevelName": "Đại học",
            "EnglishGraduateLevelName": "",
            "StudyTypeName": "Chính quy",
            "OlogyID": "CT",
            "OlogyName": "CÔNG NGHỆ THÔNG TIN",
            "OlogyEngName": null,
            "ScheduleStudyUnitID": "232LC1102D19",
            "StudyProgramID": "CQ23CT",
            "YearStudy": "2023-2024",
            "TermID": "HK02",
            "StudyUnitID": "232LC1102D",
            "CurriculumID": "LC1102D",
            "CurriculumName": "Kinh tế Chính trị Mác - Lênin",
            "CurriculumNamePrint": "Kinh tế Chính trị Mác - Lênin",
            "EnglishCurriculumName": "Political Economics of Marxism and Leninism",
            "Credits": "2",
            "CurriculumGroupID": "NC",
            "DiemTK_10": null,
            "DiemTK_4": null,
            "DiemTK_Chu": null,
            "DiemChuyenMien": "",
            "IsPass": null,
            "IsGather": "x",
            "ToanKhoa": "1",
            "NamHoc": "1",
            "HocKy": "1",
            "NotScore": "1",
            "Note": null,
            "NotComputeAverageScore": false,
            "Dat_HK": null,
            "TB_HK": null,
            "TB_HK_10": null,
            "TB_HK_4": null,
            "Dat_TL_HK": "13",
            "TongTC_DK_HK": "13",
            "TB_TL_HK": "2.62",
            "TB_TL_HK_10": "7.18",
            "TB_TL_HK_4": "2.62",
            "DiemRenLuyenHK": null,
            "CourseTime": "2023 - 2028",
            "ThoiGianDaoTao": "5",
            "ChuyenNganh": "Công nghệ thông tin",
            "AttendedDate": null,
            "T_TC_TL_TN": "13",
            "TB_TL_TN": "2.62",
            "TenXepLoai1": null,
            "Eng_TenXepLoai1": null,
            "SoHieuBang": null,
            "SoVaoSo": null,
            "QuyetDinhTotNghiep": "...",
            "NgayKyQuyetDinh": "...",
            "NgonNguDaoTao": null,
            "NotPrint": false,
            "KTESurvey": 0,
            "DGKS": 1,
            "SurveyClassID": "",
            "SurveyData": "",
            "ListOfProfessorID": "",
            "ListOfProfessorName": "",
            "_TermID": 3,
            "MD5": "4a7e420759c781e951207bafb6142a4b"
          },
          {
            "TenXepLoai": "Khá",
            "StudentID": "2312577",
            "StudentName": "TRẦN NGUYỄN TUẤN ANH",
            "StudentName_Eng": "",
            "BirthDay": "28/11/2000",
            "GenderVN": "Nam",
            "BirthPlace": "Lâm Đồng",
            "BirthPlace_Eng": "",
            "MobilePhone": "0325555077",
            "ClassStudentID": "CTK47A",
            "ClassStudentName": "CTK47A",
            "EnglishClassStudentName": null,
            "GraduateLevelID": "DH",
            "GraduateLevelName": "Đại học",
            "EnglishGraduateLevelName": "",
            "StudyTypeName": "Chính quy",
            "OlogyID": "CT",
            "OlogyName": "CÔNG NGHỆ THÔNG TIN",
            "OlogyEngName": null,
            "ScheduleStudyUnitID": "232TC1004D25",
            "StudyProgramID": "CQ23CT",
            "YearStudy": "2023-2024",
            "TermID": "HK02",
            "StudyUnitID": "232TC1004D",
            "CurriculumID": "TC1004D",
            "CurriculumName": "Giáo dục thể chất 2 - Bóng đá (Thực hành) <span style=\"color:red\">*</span>",
            "CurriculumNamePrint": "Giáo dục thể chất 2 - Bóng đá (Thực hành) *",
            "EnglishCurriculumName": "Physical Education 2 - Football",
            "Credits": "1",
            "CurriculumGroupID": "PC",
            "DiemTK_10": null,
            "DiemTK_4": null,
            "DiemTK_Chu": null,
            "DiemChuyenMien": "",
            "IsPass": null,
            "IsGather": "x",
            "ToanKhoa": "1",
            "NamHoc": "1",
            "HocKy": "1",
            "NotScore": "1",
            "Note": null,
            "NotComputeAverageScore": true,
            "Dat_HK": null,
            "TB_HK": null,
            "TB_HK_10": null,
            "TB_HK_4": null,
            "Dat_TL_HK": "13",
            "TongTC_DK_HK": "13",
            "TB_TL_HK": "2.62",
            "TB_TL_HK_10": "7.18",
            "TB_TL_HK_4": "2.62",
            "DiemRenLuyenHK": null,
            "CourseTime": "2023 - 2028",
            "ThoiGianDaoTao": "5",
            "ChuyenNganh": "Công nghệ thông tin",
            "AttendedDate": null,
            "T_TC_TL_TN": "13",
            "TB_TL_TN": "2.62",
            "TenXepLoai1": null,
            "Eng_TenXepLoai1": null,
            "SoHieuBang": null,
            "SoVaoSo": null,
            "QuyetDinhTotNghiep": "...",
            "NgayKyQuyetDinh": "...",
            "NgonNguDaoTao": null,
            "NotPrint": false,
            "KTESurvey": 0,
            "DGKS": 1,
            "SurveyClassID": "",
            "SurveyData": "",
            "ListOfProfessorID": "",
            "ListOfProfessorName": "",
            "_TermID": 3,
            "MD5": "9a3f7fcbd4dc01d0bf3d963ceeae347c"
          }
        ]
      }
    ]
  }
]
*/

func XemDiem(Token string) []byte {
	client := &http.Client{}
	req, err := http.NewRequest("GET", "https://portal-api.dlu.edu.vn/api/student/marks?ctdt=CQ23CT&&loai=SV", nil)
	if err != nil {
		log.Fatal(err)
	}
	req.Header.Set("authority", "portal-api.dlu.edu.vn")
	req.Header.Set("accept", "application/json, text/plain, */*")
	req.Header.Set("accept-language", "vi-VN,vi;q=0.9,en;q=0.8,zh-CN;q=0.7,zh;q=0.6")
	req.Header.Set("apikey", "pscRBF0zT2Mqo6vMw69YMOH43IrB2RtXBS0EHit2kzvL2auxaFJBvw==")
	req.Header.Set("authorization", "Bearer " + Token)
	req.Header.Set("clientid", "vhu")
	req.Header.Set("dnt", "1")
	req.Header.Set("origin", "https://online.dlu.edu.vn")
	req.Header.Set("referer", "https://online.dlu.edu.vn/")
	req.Header.Set("sec-ch-ua", `"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"`)
	req.Header.Set("sec-ch-ua-mobile", "?0")
	req.Header.Set("sec-ch-ua-platform", `"Windows"`)
	req.Header.Set("sec-fetch-dest", "empty")
	req.Header.Set("sec-fetch-mode", "cors")
	req.Header.Set("sec-fetch-site", "same-site")
	req.Header.Set("user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
	resp, err := client.Do(req)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()
	bodyText, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s\n", bodyText)
}
